---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

  - distro: debian9
  - distro: debian8
  - distro: ubuntu1804
  - distro: ubuntu1604

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export DOCKER="docker exec --tty ${container_id} env TERM=xterm"

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/tschifftner/4078cf2a8429d967d5e100649ff2caa9/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Check
  - ${DOCKER} /usr/local/bin/n98-magerun --version
  - ${DOCKER} /usr/local/bin/n98-magerun2 --version
  - ${DOCKER} /usr/local/bin/n98-magerun-latest --version
  - ${DOCKER} /usr/local/bin/n98-magerun2-latest --version

  # Check default repositories
  - ${DOCKER} test -e /usr/local/share/n98-magerun/modules/AOEpeople.mpmd/n98-magerun.yaml
  - ${DOCKER} test -e /usr/local/share/n98-magerun/modules/aleron75.Webgriffe_Golive/n98-magerun.yaml
  - ${DOCKER} test -e /usr/local/share/n98-magerun/modules/cmuench.magerun-addons/n98-magerun.yaml
  - ${DOCKER} test -e /usr/local/share/n98-magerun/modules/fruitcake.magerun-modman/n98-magerun.yaml
  - ${DOCKER} test -e /usr/local/share/n98-magerun/modules/hypernode.hypernode-magerun/n98-magerun.yaml
  - ${DOCKER} test -e /usr/local/share/n98-magerun/modules/kalenjordan.magerun-addons/n98-magerun.yaml
  - ${DOCKER} test -e /usr/local/share/n98-magerun/modules/peterjaap.magerun-addons/n98-magerun.yaml
  - ${DOCKER} test -e /usr/local/share/n98-magerun/modules/tschifftner.magerun-addons/n98-magerun.yaml

after_failure:
  - ${DOCKER} /usr/local/bin/n98-magerun --version
  - ${DOCKER} /usr/local/bin/n98-magerun2 --version
  - ${DOCKER} /usr/local/bin/n98-magerun-latest --version
  - ${DOCKER} /usr/local/bin/n98-magerun2-latest --version


notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
