---

- name: Download and install n98-magerun
  get_url:
    url: '{{ item.url }}'
    checksum: '{{ item.checksum | default(omit) }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 555
  when: item.install is not defined or (item.install is defined and item.install == true)
  with_items: n98_magerun_files

