---
#- name: Ensure directories exist
#  file:
#    path: '{{ item.dest | dirname }}'
#    state: directory
#  when: item.install is not defined or (item.install is defined and item.install == true)
#  with_items: n98_magerun_files

- name: Download and install n98-magerun
  get_url:
    url: '{{ item.url }}'
    checksum: '{{ item.checksum | default(omit) }}'
    dest: '{{ item.dest }}'
  when: item.install is not defined or (item.install is defined and item.install == true)
  with_items: n98_magerun_files

- name: 'Set n98-magerun chmod'
  file:
    path: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0755
  when: item.install is not defined or (item.install is defined and item.install == true)
  with_items: n98_magerun_files

- name: Install self-update cronjob
  cron:
    name: 'Regularly update {{ item.dest | basename }}'
    special_time: '{{ n98_magerun_selfupdate_specialtime }}'
    job: '{{ item.dest }} self-update >> /var/log/{{ item.dest | basename }}.log'
    user: root
    state: present
  when: item.selfupdate is not defined or (item.selfupdate is defined and item.selfupdate == true)
  with_items: n98_magerun_files
